name: Build Release Containers

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_GITHUB }}

jobs:
  publish-images:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/77991489452/locations/global/workloadIdentityPools/gh-actions-identity-pool/providers/gh-actions-identity-provider'
          service_account: 'github-actions-service-account@edgebit-containers.iam.gserviceaccount.com'

      - name: Add commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV

      - name: Configure Docker Auth
        run: |
          gcloud auth configure-docker us-docker.pkg.dev
      - name: Build No-Fly-List
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: us-docker.pkg.dev/edgebit-containers/containers/no-fly-list:${{ env.SHORT_SHA }},us-docker.pkg.dev/edgebit-containers/containers/no-fly-list:latest

      - name: Install Enclaver
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: edgebitio/enclaver
          version: tags/v0.1.0
          file: 'enclaver-linux-x86_64-v0.1.0.tar.gz'
          target: 'enclaver-linux-x86_64-v0.1.0.tar.gz'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enclaver Build & Tag
        shell: bash
        run: |
          tar -xzf enclaver-linux-x86_64-v0.1.0.tar.gz
          ls -la
          ./enclaver-linux-x86_64-v0.1.0/enclaver build -f enclaver.yaml
          docker tag no-fly-list:enclave-latest us-docker.pkg.dev/edgebit-containers/containers/no-fly-list:enclave-${{ env.SHORT_SHA }}
          docker tag no-fly-list:enclave-latest us-docker.pkg.dev/edgebit-containers/containers/no-fly-list:enclave-latest
          docker push us-docker.pkg.dev/edgebit-containers/containers/no-fly-list:enclave-latest
          docker push us-docker.pkg.dev/edgebit-containers/containers/no-fly-list:enclave-${{ env.SHORT_SHA }}
