name: Build Release Containers

on:
  push:
    branches:
      - main

jobs:
  publish-images:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/77991489452/locations/global/workloadIdentityPools/gh-actions-identity-pool/providers/gh-actions-identity-provider'
          service_account: 'github-actions-service-account@edgebit-containers.iam.gserviceaccount.com'

      - name: Add commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV

      - name: Configure Docker Auth
        run: |
          gcloud auth configure-docker us-docker.pkg.dev
      - name: Build No-Fly-List
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: us-docker.pkg.dev/edgebit-containers/containers/no-fly-list:${{ env.SHORT_SHA }},us-docker.pkg.dev/edgebit-containers/containers/no-fly-list:latest

        # This is really hacky but will be replaced with actions/download-artifact@v3 once we have public release binaries 
      - name: Extract Enclaver binary from container
        shell: bash
        run: |
          image="us-docker.pkg.dev/edgebit-containers/containers/enclaver-wrapper-base:latest"
          source_path="/usr/local/bin/enclaver"
          destination_path="./enclaver"

          container_id=$(docker create "$image")
          docker cp "$container_id:$source_path" "$destination_path"
          docker rm "$container_id"

      - name: Enclaver Build & Tag
        shell: bash
        run: |
          ./enclaver build -f enclaver.yaml
          docker tag no-fly-list:enclave-latest us-docker.pkg.dev/edgebit-containers/containers/no-fly-list:enclave-${{ env.SHORT_SHA }}
          docker tag no-fly-list:enclave-latest us-docker.pkg.dev/edgebit-containers/containers/no-fly-list:enclave-latest
          docker push us-docker.pkg.dev/edgebit-containers/containers/no-fly-list:enclave-latest
          docker push us-docker.pkg.dev/edgebit-containers/containers/no-fly-list:enclave-${{ env.SHORT_SHA }}
